// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: location/v1/location.proto

package locationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocationService_StreamLocations_FullMethodName      = "/location.v1.LocationService/StreamLocations"
	LocationService_StartJourney_FullMethodName         = "/location.v1.LocationService/StartJourney"
	LocationService_EndJourney_FullMethodName           = "/location.v1.LocationService/EndJourney"
	LocationService_GetJourneys_FullMethodName          = "/location.v1.LocationService/GetJourneys"
	LocationService_GetJourneyPoints_FullMethodName     = "/location.v1.LocationService/GetJourneyPoints"
	LocationService_RequestDeviceCode_FullMethodName    = "/location.v1.LocationService/RequestDeviceCode"
	LocationService_PollDeviceActivation_FullMethodName = "/location.v1.LocationService/PollDeviceActivation"
	LocationService_GetJourneyStats_FullMethodName      = "/location.v1.LocationService/GetJourneyStats"
	LocationService_SaveLocation_FullMethodName         = "/location.v1.LocationService/SaveLocation"
	LocationService_GetSavedLocations_FullMethodName    = "/location.v1.LocationService/GetSavedLocations"
	LocationService_DeleteSavedLocation_FullMethodName  = "/location.v1.LocationService/DeleteSavedLocation"
	LocationService_CreateShareLink_FullMethodName      = "/location.v1.LocationService/CreateShareLink"
	LocationService_GetShareLink_FullMethodName         = "/location.v1.LocationService/GetShareLink"
	LocationService_ExportJourney_FullMethodName        = "/location.v1.LocationService/ExportJourney"
	LocationService_GetDevices_FullMethodName           = "/location.v1.LocationService/GetDevices"
)

// LocationServiceClient is the client API for LocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LocationServiceClient interface {
	// Location streaming
	StreamLocations(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LocationUpdate, LocationAck], error)
	// Journey lifecycle
	StartJourney(ctx context.Context, in *StartJourneyRequest, opts ...grpc.CallOption) (*Journey, error)
	EndJourney(ctx context.Context, in *EndJourneyRequest, opts ...grpc.CallOption) (*Journey, error)
	GetJourneys(ctx context.Context, in *GetJourneysRequest, opts ...grpc.CallOption) (*GetJourneysResponse, error)
	GetJourneyPoints(ctx context.Context, in *GetJourneyPointsRequest, opts ...grpc.CallOption) (*GetJourneyPointsResponse, error)
	// Auth — Device Code flow
	RequestDeviceCode(ctx context.Context, in *DeviceCodeRequest, opts ...grpc.CallOption) (*DeviceCodeResponse, error)
	PollDeviceActivation(ctx context.Context, in *PollActivationRequest, opts ...grpc.CallOption) (*DeviceActivationResponse, error)
	// Journey stats
	GetJourneyStats(ctx context.Context, in *GetJourneyStatsRequest, opts ...grpc.CallOption) (*JourneyStats, error)
	// Saved Locations
	SaveLocation(ctx context.Context, in *SaveLocationRequest, opts ...grpc.CallOption) (*SavedLocation, error)
	GetSavedLocations(ctx context.Context, in *GetSavedLocationsRequest, opts ...grpc.CallOption) (*GetSavedLocationsResponse, error)
	DeleteSavedLocation(ctx context.Context, in *DeleteSavedLocationRequest, opts ...grpc.CallOption) (*Empty, error)
	// Share Links
	CreateShareLink(ctx context.Context, in *CreateShareLinkRequest, opts ...grpc.CallOption) (*ShareLink, error)
	GetShareLink(ctx context.Context, in *GetShareLinkRequest, opts ...grpc.CallOption) (*ShareLink, error)
	// Export
	ExportJourney(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error)
	// Devices
	GetDevices(ctx context.Context, in *GetDevicesRequest, opts ...grpc.CallOption) (*GetDevicesResponse, error)
}

type locationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocationServiceClient(cc grpc.ClientConnInterface) LocationServiceClient {
	return &locationServiceClient{cc}
}

func (c *locationServiceClient) StreamLocations(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LocationUpdate, LocationAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LocationService_ServiceDesc.Streams[0], LocationService_StreamLocations_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LocationUpdate, LocationAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocationService_StreamLocationsClient = grpc.ClientStreamingClient[LocationUpdate, LocationAck]

func (c *locationServiceClient) StartJourney(ctx context.Context, in *StartJourneyRequest, opts ...grpc.CallOption) (*Journey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Journey)
	err := c.cc.Invoke(ctx, LocationService_StartJourney_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) EndJourney(ctx context.Context, in *EndJourneyRequest, opts ...grpc.CallOption) (*Journey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Journey)
	err := c.cc.Invoke(ctx, LocationService_EndJourney_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) GetJourneys(ctx context.Context, in *GetJourneysRequest, opts ...grpc.CallOption) (*GetJourneysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJourneysResponse)
	err := c.cc.Invoke(ctx, LocationService_GetJourneys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) GetJourneyPoints(ctx context.Context, in *GetJourneyPointsRequest, opts ...grpc.CallOption) (*GetJourneyPointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJourneyPointsResponse)
	err := c.cc.Invoke(ctx, LocationService_GetJourneyPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) RequestDeviceCode(ctx context.Context, in *DeviceCodeRequest, opts ...grpc.CallOption) (*DeviceCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceCodeResponse)
	err := c.cc.Invoke(ctx, LocationService_RequestDeviceCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) PollDeviceActivation(ctx context.Context, in *PollActivationRequest, opts ...grpc.CallOption) (*DeviceActivationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceActivationResponse)
	err := c.cc.Invoke(ctx, LocationService_PollDeviceActivation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) GetJourneyStats(ctx context.Context, in *GetJourneyStatsRequest, opts ...grpc.CallOption) (*JourneyStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JourneyStats)
	err := c.cc.Invoke(ctx, LocationService_GetJourneyStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) SaveLocation(ctx context.Context, in *SaveLocationRequest, opts ...grpc.CallOption) (*SavedLocation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SavedLocation)
	err := c.cc.Invoke(ctx, LocationService_SaveLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) GetSavedLocations(ctx context.Context, in *GetSavedLocationsRequest, opts ...grpc.CallOption) (*GetSavedLocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSavedLocationsResponse)
	err := c.cc.Invoke(ctx, LocationService_GetSavedLocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) DeleteSavedLocation(ctx context.Context, in *DeleteSavedLocationRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, LocationService_DeleteSavedLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) CreateShareLink(ctx context.Context, in *CreateShareLinkRequest, opts ...grpc.CallOption) (*ShareLink, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShareLink)
	err := c.cc.Invoke(ctx, LocationService_CreateShareLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) GetShareLink(ctx context.Context, in *GetShareLinkRequest, opts ...grpc.CallOption) (*ShareLink, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShareLink)
	err := c.cc.Invoke(ctx, LocationService_GetShareLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) ExportJourney(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, LocationService_ExportJourney_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) GetDevices(ctx context.Context, in *GetDevicesRequest, opts ...grpc.CallOption) (*GetDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDevicesResponse)
	err := c.cc.Invoke(ctx, LocationService_GetDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocationServiceServer is the server API for LocationService service.
// All implementations must embed UnimplementedLocationServiceServer
// for forward compatibility.
type LocationServiceServer interface {
	// Location streaming
	StreamLocations(grpc.ClientStreamingServer[LocationUpdate, LocationAck]) error
	// Journey lifecycle
	StartJourney(context.Context, *StartJourneyRequest) (*Journey, error)
	EndJourney(context.Context, *EndJourneyRequest) (*Journey, error)
	GetJourneys(context.Context, *GetJourneysRequest) (*GetJourneysResponse, error)
	GetJourneyPoints(context.Context, *GetJourneyPointsRequest) (*GetJourneyPointsResponse, error)
	// Auth — Device Code flow
	RequestDeviceCode(context.Context, *DeviceCodeRequest) (*DeviceCodeResponse, error)
	PollDeviceActivation(context.Context, *PollActivationRequest) (*DeviceActivationResponse, error)
	// Journey stats
	GetJourneyStats(context.Context, *GetJourneyStatsRequest) (*JourneyStats, error)
	// Saved Locations
	SaveLocation(context.Context, *SaveLocationRequest) (*SavedLocation, error)
	GetSavedLocations(context.Context, *GetSavedLocationsRequest) (*GetSavedLocationsResponse, error)
	DeleteSavedLocation(context.Context, *DeleteSavedLocationRequest) (*Empty, error)
	// Share Links
	CreateShareLink(context.Context, *CreateShareLinkRequest) (*ShareLink, error)
	GetShareLink(context.Context, *GetShareLinkRequest) (*ShareLink, error)
	// Export
	ExportJourney(context.Context, *ExportRequest) (*ExportResponse, error)
	// Devices
	GetDevices(context.Context, *GetDevicesRequest) (*GetDevicesResponse, error)
	mustEmbedUnimplementedLocationServiceServer()
}

// UnimplementedLocationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocationServiceServer struct{}

func (UnimplementedLocationServiceServer) StreamLocations(grpc.ClientStreamingServer[LocationUpdate, LocationAck]) error {
	return status.Error(codes.Unimplemented, "method StreamLocations not implemented")
}
func (UnimplementedLocationServiceServer) StartJourney(context.Context, *StartJourneyRequest) (*Journey, error) {
	return nil, status.Error(codes.Unimplemented, "method StartJourney not implemented")
}
func (UnimplementedLocationServiceServer) EndJourney(context.Context, *EndJourneyRequest) (*Journey, error) {
	return nil, status.Error(codes.Unimplemented, "method EndJourney not implemented")
}
func (UnimplementedLocationServiceServer) GetJourneys(context.Context, *GetJourneysRequest) (*GetJourneysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJourneys not implemented")
}
func (UnimplementedLocationServiceServer) GetJourneyPoints(context.Context, *GetJourneyPointsRequest) (*GetJourneyPointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJourneyPoints not implemented")
}
func (UnimplementedLocationServiceServer) RequestDeviceCode(context.Context, *DeviceCodeRequest) (*DeviceCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestDeviceCode not implemented")
}
func (UnimplementedLocationServiceServer) PollDeviceActivation(context.Context, *PollActivationRequest) (*DeviceActivationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PollDeviceActivation not implemented")
}
func (UnimplementedLocationServiceServer) GetJourneyStats(context.Context, *GetJourneyStatsRequest) (*JourneyStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJourneyStats not implemented")
}
func (UnimplementedLocationServiceServer) SaveLocation(context.Context, *SaveLocationRequest) (*SavedLocation, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveLocation not implemented")
}
func (UnimplementedLocationServiceServer) GetSavedLocations(context.Context, *GetSavedLocationsRequest) (*GetSavedLocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSavedLocations not implemented")
}
func (UnimplementedLocationServiceServer) DeleteSavedLocation(context.Context, *DeleteSavedLocationRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSavedLocation not implemented")
}
func (UnimplementedLocationServiceServer) CreateShareLink(context.Context, *CreateShareLinkRequest) (*ShareLink, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShareLink not implemented")
}
func (UnimplementedLocationServiceServer) GetShareLink(context.Context, *GetShareLinkRequest) (*ShareLink, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShareLink not implemented")
}
func (UnimplementedLocationServiceServer) ExportJourney(context.Context, *ExportRequest) (*ExportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportJourney not implemented")
}
func (UnimplementedLocationServiceServer) GetDevices(context.Context, *GetDevicesRequest) (*GetDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDevices not implemented")
}
func (UnimplementedLocationServiceServer) mustEmbedUnimplementedLocationServiceServer() {}
func (UnimplementedLocationServiceServer) testEmbeddedByValue()                         {}

// UnsafeLocationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocationServiceServer will
// result in compilation errors.
type UnsafeLocationServiceServer interface {
	mustEmbedUnimplementedLocationServiceServer()
}

func RegisterLocationServiceServer(s grpc.ServiceRegistrar, srv LocationServiceServer) {
	// If the following call panics, it indicates UnimplementedLocationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocationService_ServiceDesc, srv)
}

func _LocationService_StreamLocations_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LocationServiceServer).StreamLocations(&grpc.GenericServerStream[LocationUpdate, LocationAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocationService_StreamLocationsServer = grpc.ClientStreamingServer[LocationUpdate, LocationAck]

func _LocationService_StartJourney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartJourneyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).StartJourney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_StartJourney_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).StartJourney(ctx, req.(*StartJourneyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_EndJourney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndJourneyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).EndJourney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_EndJourney_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).EndJourney(ctx, req.(*EndJourneyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_GetJourneys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJourneysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).GetJourneys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_GetJourneys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).GetJourneys(ctx, req.(*GetJourneysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_GetJourneyPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJourneyPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).GetJourneyPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_GetJourneyPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).GetJourneyPoints(ctx, req.(*GetJourneyPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_RequestDeviceCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).RequestDeviceCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_RequestDeviceCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).RequestDeviceCode(ctx, req.(*DeviceCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_PollDeviceActivation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollActivationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).PollDeviceActivation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_PollDeviceActivation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).PollDeviceActivation(ctx, req.(*PollActivationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_GetJourneyStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJourneyStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).GetJourneyStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_GetJourneyStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).GetJourneyStats(ctx, req.(*GetJourneyStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_SaveLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).SaveLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_SaveLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).SaveLocation(ctx, req.(*SaveLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_GetSavedLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSavedLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).GetSavedLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_GetSavedLocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).GetSavedLocations(ctx, req.(*GetSavedLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_DeleteSavedLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSavedLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).DeleteSavedLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_DeleteSavedLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).DeleteSavedLocation(ctx, req.(*DeleteSavedLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_CreateShareLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShareLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).CreateShareLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_CreateShareLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).CreateShareLink(ctx, req.(*CreateShareLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_GetShareLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShareLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).GetShareLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_GetShareLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).GetShareLink(ctx, req.(*GetShareLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_ExportJourney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).ExportJourney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_ExportJourney_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).ExportJourney(ctx, req.(*ExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_GetDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).GetDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_GetDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).GetDevices(ctx, req.(*GetDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LocationService_ServiceDesc is the grpc.ServiceDesc for LocationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "location.v1.LocationService",
	HandlerType: (*LocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartJourney",
			Handler:    _LocationService_StartJourney_Handler,
		},
		{
			MethodName: "EndJourney",
			Handler:    _LocationService_EndJourney_Handler,
		},
		{
			MethodName: "GetJourneys",
			Handler:    _LocationService_GetJourneys_Handler,
		},
		{
			MethodName: "GetJourneyPoints",
			Handler:    _LocationService_GetJourneyPoints_Handler,
		},
		{
			MethodName: "RequestDeviceCode",
			Handler:    _LocationService_RequestDeviceCode_Handler,
		},
		{
			MethodName: "PollDeviceActivation",
			Handler:    _LocationService_PollDeviceActivation_Handler,
		},
		{
			MethodName: "GetJourneyStats",
			Handler:    _LocationService_GetJourneyStats_Handler,
		},
		{
			MethodName: "SaveLocation",
			Handler:    _LocationService_SaveLocation_Handler,
		},
		{
			MethodName: "GetSavedLocations",
			Handler:    _LocationService_GetSavedLocations_Handler,
		},
		{
			MethodName: "DeleteSavedLocation",
			Handler:    _LocationService_DeleteSavedLocation_Handler,
		},
		{
			MethodName: "CreateShareLink",
			Handler:    _LocationService_CreateShareLink_Handler,
		},
		{
			MethodName: "GetShareLink",
			Handler:    _LocationService_GetShareLink_Handler,
		},
		{
			MethodName: "ExportJourney",
			Handler:    _LocationService_ExportJourney_Handler,
		},
		{
			MethodName: "GetDevices",
			Handler:    _LocationService_GetDevices_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLocations",
			Handler:       _LocationService_StreamLocations_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "location/v1/location.proto",
}
