// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: location/v1/location.proto

package locationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocationUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	JourneyId     string                 `protobuf:"bytes,2,opt,name=journey_id,json=journeyId,proto3" json:"journey_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Accuracy      float32                `protobuf:"fixed32,5,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Speed         float32                `protobuf:"fixed32,6,opt,name=speed,proto3" json:"speed,omitempty"`
	Altitude      float32                `protobuf:"fixed32,7,opt,name=altitude,proto3" json:"altitude,omitempty"`
	Heading       float32                `protobuf:"fixed32,8,opt,name=heading,proto3" json:"heading,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,9,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Source        string                 `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
	HeartRate     float32                `protobuf:"fixed32,11,opt,name=heart_rate,json=heartRate,proto3" json:"heart_rate,omitempty"`
	TransportMode string                 `protobuf:"bytes,12,opt,name=transport_mode,json=transportMode,proto3" json:"transport_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationUpdate) Reset() {
	*x = LocationUpdate{}
	mi := &file_location_v1_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationUpdate) ProtoMessage() {}

func (x *LocationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationUpdate.ProtoReflect.Descriptor instead.
func (*LocationUpdate) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{0}
}

func (x *LocationUpdate) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LocationUpdate) GetJourneyId() string {
	if x != nil {
		return x.JourneyId
	}
	return ""
}

func (x *LocationUpdate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LocationUpdate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LocationUpdate) GetAccuracy() float32 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *LocationUpdate) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *LocationUpdate) GetAltitude() float32 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *LocationUpdate) GetHeading() float32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *LocationUpdate) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *LocationUpdate) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LocationUpdate) GetHeartRate() float32 {
	if x != nil {
		return x.HeartRate
	}
	return 0
}

func (x *LocationUpdate) GetTransportMode() string {
	if x != nil {
		return x.TransportMode
	}
	return ""
}

type LocationAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PointsReceived int32                  `protobuf:"varint,1,opt,name=points_received,json=pointsReceived,proto3" json:"points_received,omitempty"`
	JourneyId      string                 `protobuf:"bytes,2,opt,name=journey_id,json=journeyId,proto3" json:"journey_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocationAck) Reset() {
	*x = LocationAck{}
	mi := &file_location_v1_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationAck) ProtoMessage() {}

func (x *LocationAck) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationAck.ProtoReflect.Descriptor instead.
func (*LocationAck) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{1}
}

func (x *LocationAck) GetPointsReceived() int32 {
	if x != nil {
		return x.PointsReceived
	}
	return 0
}

func (x *LocationAck) GetJourneyId() string {
	if x != nil {
		return x.JourneyId
	}
	return ""
}

type LocationPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Accuracy      float32                `protobuf:"fixed32,3,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Speed         float32                `protobuf:"fixed32,4,opt,name=speed,proto3" json:"speed,omitempty"`
	Altitude      float32                `protobuf:"fixed32,5,opt,name=altitude,proto3" json:"altitude,omitempty"`
	Heading       float32                `protobuf:"fixed32,6,opt,name=heading,proto3" json:"heading,omitempty"`
	RecordedAt    int64                  `protobuf:"varint,7,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationPoint) Reset() {
	*x = LocationPoint{}
	mi := &file_location_v1_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationPoint) ProtoMessage() {}

func (x *LocationPoint) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationPoint.ProtoReflect.Descriptor instead.
func (*LocationPoint) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{2}
}

func (x *LocationPoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LocationPoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LocationPoint) GetAccuracy() float32 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *LocationPoint) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *LocationPoint) GetAltitude() float32 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *LocationPoint) GetHeading() float32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *LocationPoint) GetRecordedAt() int64 {
	if x != nil {
		return x.RecordedAt
	}
	return 0
}

type StartJourneyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJourneyRequest) Reset() {
	*x = StartJourneyRequest{}
	mi := &file_location_v1_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJourneyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJourneyRequest) ProtoMessage() {}

func (x *StartJourneyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJourneyRequest.ProtoReflect.Descriptor instead.
func (*StartJourneyRequest) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{3}
}

func (x *StartJourneyRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *StartJourneyRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type EndJourneyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JourneyId     string                 `protobuf:"bytes,1,opt,name=journey_id,json=journeyId,proto3" json:"journey_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndJourneyRequest) Reset() {
	*x = EndJourneyRequest{}
	mi := &file_location_v1_location_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndJourneyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndJourneyRequest) ProtoMessage() {}

func (x *EndJourneyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndJourneyRequest.ProtoReflect.Descriptor instead.
func (*EndJourneyRequest) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{4}
}

func (x *EndJourneyRequest) GetJourneyId() string {
	if x != nil {
		return x.JourneyId
	}
	return ""
}

type Journey struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId       string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Label          string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	StartedAt      int64                  `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt        int64                  `protobuf:"varint,5,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	TotalDistanceM float64                `protobuf:"fixed64,6,opt,name=total_distance_m,json=totalDistanceM,proto3" json:"total_distance_m,omitempty"`
	PointCount     int32                  `protobuf:"varint,7,opt,name=point_count,json=pointCount,proto3" json:"point_count,omitempty"`
	TransportMode  string                 `protobuf:"bytes,8,opt,name=transport_mode,json=transportMode,proto3" json:"transport_mode,omitempty"`
	StartPlace     string                 `protobuf:"bytes,9,opt,name=start_place,json=startPlace,proto3" json:"start_place,omitempty"`
	EndPlace       string                 `protobuf:"bytes,10,opt,name=end_place,json=endPlace,proto3" json:"end_place,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Journey) Reset() {
	*x = Journey{}
	mi := &file_location_v1_location_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Journey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Journey) ProtoMessage() {}

func (x *Journey) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Journey.ProtoReflect.Descriptor instead.
func (*Journey) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{5}
}

func (x *Journey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Journey) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Journey) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Journey) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Journey) GetEndedAt() int64 {
	if x != nil {
		return x.EndedAt
	}
	return 0
}

func (x *Journey) GetTotalDistanceM() float64 {
	if x != nil {
		return x.TotalDistanceM
	}
	return 0
}

func (x *Journey) GetPointCount() int32 {
	if x != nil {
		return x.PointCount
	}
	return 0
}

func (x *Journey) GetTransportMode() string {
	if x != nil {
		return x.TransportMode
	}
	return ""
}

func (x *Journey) GetStartPlace() string {
	if x != nil {
		return x.StartPlace
	}
	return ""
}

func (x *Journey) GetEndPlace() string {
	if x != nil {
		return x.EndPlace
	}
	return ""
}

type GetJourneysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJourneysRequest) Reset() {
	*x = GetJourneysRequest{}
	mi := &file_location_v1_location_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJourneysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJourneysRequest) ProtoMessage() {}

func (x *GetJourneysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJourneysRequest.ProtoReflect.Descriptor instead.
func (*GetJourneysRequest) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{6}
}

func (x *GetJourneysRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetJourneysRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetJourneysRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetJourneysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Journeys      []*Journey             `protobuf:"bytes,1,rep,name=journeys,proto3" json:"journeys,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJourneysResponse) Reset() {
	*x = GetJourneysResponse{}
	mi := &file_location_v1_location_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJourneysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJourneysResponse) ProtoMessage() {}

func (x *GetJourneysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJourneysResponse.ProtoReflect.Descriptor instead.
func (*GetJourneysResponse) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{7}
}

func (x *GetJourneysResponse) GetJourneys() []*Journey {
	if x != nil {
		return x.Journeys
	}
	return nil
}

func (x *GetJourneysResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetJourneyPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JourneyId     string                 `protobuf:"bytes,1,opt,name=journey_id,json=journeyId,proto3" json:"journey_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJourneyPointsRequest) Reset() {
	*x = GetJourneyPointsRequest{}
	mi := &file_location_v1_location_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJourneyPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJourneyPointsRequest) ProtoMessage() {}

func (x *GetJourneyPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJourneyPointsRequest.ProtoReflect.Descriptor instead.
func (*GetJourneyPointsRequest) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{8}
}

func (x *GetJourneyPointsRequest) GetJourneyId() string {
	if x != nil {
		return x.JourneyId
	}
	return ""
}

type GetJourneyPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*LocationPoint       `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJourneyPointsResponse) Reset() {
	*x = GetJourneyPointsResponse{}
	mi := &file_location_v1_location_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJourneyPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJourneyPointsResponse) ProtoMessage() {}

func (x *GetJourneyPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJourneyPointsResponse.ProtoReflect.Descriptor instead.
func (*GetJourneyPointsResponse) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{9}
}

func (x *GetJourneyPointsResponse) GetPoints() []*LocationPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type DeviceCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceName    string                 `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"` // "Pixel 8 Pro" or "Galaxy Watch 6"
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`                       // "android" | "wearos"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCodeRequest) Reset() {
	*x = DeviceCodeRequest{}
	mi := &file_location_v1_location_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCodeRequest) ProtoMessage() {}

func (x *DeviceCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCodeRequest.ProtoReflect.Descriptor instead.
func (*DeviceCodeRequest) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{10}
}

func (x *DeviceCodeRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *DeviceCodeRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type DeviceCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceCode    string                 `protobuf:"bytes,1,opt,name=device_code,json=deviceCode,proto3" json:"device_code,omitempty"` // 5-char alphanumeric e.g. "A3K9M"
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`   // code expires in 10 minutes
	Interval      int32                  `protobuf:"varint,3,opt,name=interval,proto3" json:"interval,omitempty"`                      // poll interval in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCodeResponse) Reset() {
	*x = DeviceCodeResponse{}
	mi := &file_location_v1_location_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCodeResponse) ProtoMessage() {}

func (x *DeviceCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCodeResponse.ProtoReflect.Descriptor instead.
func (*DeviceCodeResponse) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{11}
}

func (x *DeviceCodeResponse) GetDeviceCode() string {
	if x != nil {
		return x.DeviceCode
	}
	return ""
}

func (x *DeviceCodeResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *DeviceCodeResponse) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

type PollActivationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceCode    string                 `protobuf:"bytes,1,opt,name=device_code,json=deviceCode,proto3" json:"device_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollActivationRequest) Reset() {
	*x = PollActivationRequest{}
	mi := &file_location_v1_location_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollActivationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollActivationRequest) ProtoMessage() {}

func (x *PollActivationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollActivationRequest.ProtoReflect.Descriptor instead.
func (*PollActivationRequest) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{12}
}

func (x *PollActivationRequest) GetDeviceCode() string {
	if x != nil {
		return x.DeviceCode
	}
	return ""
}

type DeviceActivationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activated     bool                   `protobuf:"varint,1,opt,name=activated,proto3" json:"activated,omitempty"`
	DeviceToken   string                 `protobuf:"bytes,2,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"` // JWT — empty if not yet activated
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`          // assigned UUID
	DeviceName    string                 `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceActivationResponse) Reset() {
	*x = DeviceActivationResponse{}
	mi := &file_location_v1_location_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceActivationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceActivationResponse) ProtoMessage() {}

func (x *DeviceActivationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceActivationResponse.ProtoReflect.Descriptor instead.
func (*DeviceActivationResponse) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{13}
}

func (x *DeviceActivationResponse) GetActivated() bool {
	if x != nil {
		return x.Activated
	}
	return false
}

func (x *DeviceActivationResponse) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *DeviceActivationResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceActivationResponse) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

type GetJourneyStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"` // "day" | "week" | "month"
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`  // number of periods
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJourneyStatsRequest) Reset() {
	*x = GetJourneyStatsRequest{}
	mi := &file_location_v1_location_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJourneyStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJourneyStatsRequest) ProtoMessage() {}

func (x *GetJourneyStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJourneyStatsRequest.ProtoReflect.Descriptor instead.
func (*GetJourneyStatsRequest) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{14}
}

func (x *GetJourneyStatsRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetJourneyStatsRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetJourneyStatsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type JourneyStats struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	DeviceId              string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	TotalJourneys         int32                  `protobuf:"varint,2,opt,name=total_journeys,json=totalJourneys,proto3" json:"total_journeys,omitempty"`
	TotalDistanceM        float64                `protobuf:"fixed64,3,opt,name=total_distance_m,json=totalDistanceM,proto3" json:"total_distance_m,omitempty"`
	TotalDurationMs       int64                  `protobuf:"varint,4,opt,name=total_duration_ms,json=totalDurationMs,proto3" json:"total_duration_ms,omitempty"`
	AvgSpeed              float64                `protobuf:"fixed64,5,opt,name=avg_speed,json=avgSpeed,proto3" json:"avg_speed,omitempty"`
	MaxSpeed              float64                `protobuf:"fixed64,6,opt,name=max_speed,json=maxSpeed,proto3" json:"max_speed,omitempty"`
	AvgDistancePerJourney float64                `protobuf:"fixed64,7,opt,name=avg_distance_per_journey,json=avgDistancePerJourney,proto3" json:"avg_distance_per_journey,omitempty"`
	Daily                 []*DayStats            `protobuf:"bytes,8,rep,name=daily,proto3" json:"daily,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *JourneyStats) Reset() {
	*x = JourneyStats{}
	mi := &file_location_v1_location_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JourneyStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JourneyStats) ProtoMessage() {}

func (x *JourneyStats) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JourneyStats.ProtoReflect.Descriptor instead.
func (*JourneyStats) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{15}
}

func (x *JourneyStats) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *JourneyStats) GetTotalJourneys() int32 {
	if x != nil {
		return x.TotalJourneys
	}
	return 0
}

func (x *JourneyStats) GetTotalDistanceM() float64 {
	if x != nil {
		return x.TotalDistanceM
	}
	return 0
}

func (x *JourneyStats) GetTotalDurationMs() int64 {
	if x != nil {
		return x.TotalDurationMs
	}
	return 0
}

func (x *JourneyStats) GetAvgSpeed() float64 {
	if x != nil {
		return x.AvgSpeed
	}
	return 0
}

func (x *JourneyStats) GetMaxSpeed() float64 {
	if x != nil {
		return x.MaxSpeed
	}
	return 0
}

func (x *JourneyStats) GetAvgDistancePerJourney() float64 {
	if x != nil {
		return x.AvgDistancePerJourney
	}
	return 0
}

func (x *JourneyStats) GetDaily() []*DayStats {
	if x != nil {
		return x.Daily
	}
	return nil
}

type DayStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // "2026-06-20"
	JourneyCount  int32                  `protobuf:"varint,2,opt,name=journey_count,json=journeyCount,proto3" json:"journey_count,omitempty"`
	DistanceM     float64                `protobuf:"fixed64,3,opt,name=distance_m,json=distanceM,proto3" json:"distance_m,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DayStats) Reset() {
	*x = DayStats{}
	mi := &file_location_v1_location_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DayStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayStats) ProtoMessage() {}

func (x *DayStats) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayStats.ProtoReflect.Descriptor instead.
func (*DayStats) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{16}
}

func (x *DayStats) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DayStats) GetJourneyCount() int32 {
	if x != nil {
		return x.JourneyCount
	}
	return 0
}

func (x *DayStats) GetDistanceM() float64 {
	if x != nil {
		return x.DistanceM
	}
	return 0
}

func (x *DayStats) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type SaveLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // "Home", "Work", "Gym"
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	RadiusM       float32                `protobuf:"fixed32,5,opt,name=radius_m,json=radiusM,proto3" json:"radius_m,omitempty"` // geofence radius in meters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveLocationRequest) Reset() {
	*x = SaveLocationRequest{}
	mi := &file_location_v1_location_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveLocationRequest) ProtoMessage() {}

func (x *SaveLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveLocationRequest.ProtoReflect.Descriptor instead.
func (*SaveLocationRequest) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{17}
}

func (x *SaveLocationRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SaveLocationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveLocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SaveLocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *SaveLocationRequest) GetRadiusM() float32 {
	if x != nil {
		return x.RadiusM
	}
	return 0
}

type SavedLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	RadiusM       float32                `protobuf:"fixed32,6,opt,name=radius_m,json=radiusM,proto3" json:"radius_m,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavedLocation) Reset() {
	*x = SavedLocation{}
	mi := &file_location_v1_location_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavedLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavedLocation) ProtoMessage() {}

func (x *SavedLocation) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavedLocation.ProtoReflect.Descriptor instead.
func (*SavedLocation) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{18}
}

func (x *SavedLocation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SavedLocation) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SavedLocation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SavedLocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SavedLocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *SavedLocation) GetRadiusM() float32 {
	if x != nil {
		return x.RadiusM
	}
	return 0
}

func (x *SavedLocation) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetSavedLocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSavedLocationsRequest) Reset() {
	*x = GetSavedLocationsRequest{}
	mi := &file_location_v1_location_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSavedLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSavedLocationsRequest) ProtoMessage() {}

func (x *GetSavedLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSavedLocationsRequest.ProtoReflect.Descriptor instead.
func (*GetSavedLocationsRequest) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{19}
}

func (x *GetSavedLocationsRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type GetSavedLocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*SavedLocation       `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSavedLocationsResponse) Reset() {
	*x = GetSavedLocationsResponse{}
	mi := &file_location_v1_location_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSavedLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSavedLocationsResponse) ProtoMessage() {}

func (x *GetSavedLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSavedLocationsResponse.ProtoReflect.Descriptor instead.
func (*GetSavedLocationsResponse) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{20}
}

func (x *GetSavedLocationsResponse) GetLocations() []*SavedLocation {
	if x != nil {
		return x.Locations
	}
	return nil
}

type DeleteSavedLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    string                 `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSavedLocationRequest) Reset() {
	*x = DeleteSavedLocationRequest{}
	mi := &file_location_v1_location_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSavedLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSavedLocationRequest) ProtoMessage() {}

func (x *DeleteSavedLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSavedLocationRequest.ProtoReflect.Descriptor instead.
func (*DeleteSavedLocationRequest) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteSavedLocationRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

type CreateShareLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JourneyId     string                 `protobuf:"bytes,1,opt,name=journey_id,json=journeyId,proto3" json:"journey_id,omitempty"`
	DurationHours int64                  `protobuf:"varint,2,opt,name=duration_hours,json=durationHours,proto3" json:"duration_hours,omitempty"` // 0 = no expiry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShareLinkRequest) Reset() {
	*x = CreateShareLinkRequest{}
	mi := &file_location_v1_location_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShareLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShareLinkRequest) ProtoMessage() {}

func (x *CreateShareLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShareLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateShareLinkRequest) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{22}
}

func (x *CreateShareLinkRequest) GetJourneyId() string {
	if x != nil {
		return x.JourneyId
	}
	return ""
}

func (x *CreateShareLinkRequest) GetDurationHours() int64 {
	if x != nil {
		return x.DurationHours
	}
	return 0
}

type ShareLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JourneyId     string                 `protobuf:"bytes,2,opt,name=journey_id,json=journeyId,proto3" json:"journey_id,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Expired       bool                   `protobuf:"varint,5,opt,name=expired,proto3" json:"expired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareLink) Reset() {
	*x = ShareLink{}
	mi := &file_location_v1_location_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareLink) ProtoMessage() {}

func (x *ShareLink) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareLink.ProtoReflect.Descriptor instead.
func (*ShareLink) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{23}
}

func (x *ShareLink) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShareLink) GetJourneyId() string {
	if x != nil {
		return x.JourneyId
	}
	return ""
}

func (x *ShareLink) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ShareLink) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *ShareLink) GetExpired() bool {
	if x != nil {
		return x.Expired
	}
	return false
}

type GetShareLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareId       string                 `protobuf:"bytes,1,opt,name=share_id,json=shareId,proto3" json:"share_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareLinkRequest) Reset() {
	*x = GetShareLinkRequest{}
	mi := &file_location_v1_location_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareLinkRequest) ProtoMessage() {}

func (x *GetShareLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareLinkRequest.ProtoReflect.Descriptor instead.
func (*GetShareLinkRequest) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{24}
}

func (x *GetShareLinkRequest) GetShareId() string {
	if x != nil {
		return x.ShareId
	}
	return ""
}

type ExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JourneyId     string                 `protobuf:"bytes,1,opt,name=journey_id,json=journeyId,proto3" json:"journey_id,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"` // "gpx" | "geojson" | "csv"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_location_v1_location_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{25}
}

func (x *ExportRequest) GetJourneyId() string {
	if x != nil {
		return x.JourneyId
	}
	return ""
}

func (x *ExportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type ExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_location_v1_location_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{26}
}

func (x *ExportResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ExportResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	LastSeen      int64                  `protobuf:"varint,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_location_v1_location_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{27}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Device) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *Device) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type GetDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevicesRequest) Reset() {
	*x = GetDevicesRequest{}
	mi := &file_location_v1_location_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesRequest) ProtoMessage() {}

func (x *GetDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesRequest.ProtoReflect.Descriptor instead.
func (*GetDevicesRequest) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{28}
}

type GetDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevicesResponse) Reset() {
	*x = GetDevicesResponse{}
	mi := &file_location_v1_location_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesResponse) ProtoMessage() {}

func (x *GetDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesResponse.ProtoReflect.Descriptor instead.
func (*GetDevicesResponse) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{29}
}

func (x *GetDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_location_v1_location_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{30}
}

var File_location_v1_location_proto protoreflect.FileDescriptor

const file_location_v1_location_proto_rawDesc = "" +
	"\n" +
	"\x1alocation/v1/location.proto\x12\vlocation.v1\"\xef\x02\n" +
	"\x0eLocationUpdate\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"journey_id\x18\x02 \x01(\tR\tjourneyId\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baccuracy\x18\x05 \x01(\x02R\baccuracy\x12\x14\n" +
	"\x05speed\x18\x06 \x01(\x02R\x05speed\x12\x1a\n" +
	"\baltitude\x18\a \x01(\x02R\baltitude\x12\x18\n" +
	"\aheading\x18\b \x01(\x02R\aheading\x12!\n" +
	"\ftimestamp_ms\x18\t \x01(\x03R\vtimestampMs\x12\x16\n" +
	"\x06source\x18\n" +
	" \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"heart_rate\x18\v \x01(\x02R\theartRate\x12%\n" +
	"\x0etransport_mode\x18\f \x01(\tR\rtransportMode\"U\n" +
	"\vLocationAck\x12'\n" +
	"\x0fpoints_received\x18\x01 \x01(\x05R\x0epointsReceived\x12\x1d\n" +
	"\n" +
	"journey_id\x18\x02 \x01(\tR\tjourneyId\"\xd2\x01\n" +
	"\rLocationPoint\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baccuracy\x18\x03 \x01(\x02R\baccuracy\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x02R\x05speed\x12\x1a\n" +
	"\baltitude\x18\x05 \x01(\x02R\baltitude\x12\x18\n" +
	"\aheading\x18\x06 \x01(\x02R\aheading\x12\x1f\n" +
	"\vrecorded_at\x18\a \x01(\x03R\n" +
	"recordedAt\"H\n" +
	"\x13StartJourneyRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"2\n" +
	"\x11EndJourneyRequest\x12\x1d\n" +
	"\n" +
	"journey_id\x18\x01 \x01(\tR\tjourneyId\"\xb6\x02\n" +
	"\aJourney\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03R\tstartedAt\x12\x19\n" +
	"\bended_at\x18\x05 \x01(\x03R\aendedAt\x12(\n" +
	"\x10total_distance_m\x18\x06 \x01(\x01R\x0etotalDistanceM\x12\x1f\n" +
	"\vpoint_count\x18\a \x01(\x05R\n" +
	"pointCount\x12%\n" +
	"\x0etransport_mode\x18\b \x01(\tR\rtransportMode\x12\x1f\n" +
	"\vstart_place\x18\t \x01(\tR\n" +
	"startPlace\x12\x1b\n" +
	"\tend_place\x18\n" +
	" \x01(\tR\bendPlace\"_\n" +
	"\x12GetJourneysRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"]\n" +
	"\x13GetJourneysResponse\x120\n" +
	"\bjourneys\x18\x01 \x03(\v2\x14.location.v1.JourneyR\bjourneys\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"8\n" +
	"\x17GetJourneyPointsRequest\x12\x1d\n" +
	"\n" +
	"journey_id\x18\x01 \x01(\tR\tjourneyId\"N\n" +
	"\x18GetJourneyPointsResponse\x122\n" +
	"\x06points\x18\x01 \x03(\v2\x1a.location.v1.LocationPointR\x06points\"P\n" +
	"\x11DeviceCodeRequest\x12\x1f\n" +
	"\vdevice_name\x18\x01 \x01(\tR\n" +
	"deviceName\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\"p\n" +
	"\x12DeviceCodeResponse\x12\x1f\n" +
	"\vdevice_code\x18\x01 \x01(\tR\n" +
	"deviceCode\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\x12\x1a\n" +
	"\binterval\x18\x03 \x01(\x05R\binterval\"8\n" +
	"\x15PollActivationRequest\x12\x1f\n" +
	"\vdevice_code\x18\x01 \x01(\tR\n" +
	"deviceCode\"\x99\x01\n" +
	"\x18DeviceActivationResponse\x12\x1c\n" +
	"\tactivated\x18\x01 \x01(\bR\tactivated\x12!\n" +
	"\fdevice_token\x18\x02 \x01(\tR\vdeviceToken\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\tR\n" +
	"deviceName\"c\n" +
	"\x16GetJourneyStatsRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xc8\x02\n" +
	"\fJourneyStats\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12%\n" +
	"\x0etotal_journeys\x18\x02 \x01(\x05R\rtotalJourneys\x12(\n" +
	"\x10total_distance_m\x18\x03 \x01(\x01R\x0etotalDistanceM\x12*\n" +
	"\x11total_duration_ms\x18\x04 \x01(\x03R\x0ftotalDurationMs\x12\x1b\n" +
	"\tavg_speed\x18\x05 \x01(\x01R\bavgSpeed\x12\x1b\n" +
	"\tmax_speed\x18\x06 \x01(\x01R\bmaxSpeed\x127\n" +
	"\x18avg_distance_per_journey\x18\a \x01(\x01R\x15avgDistancePerJourney\x12+\n" +
	"\x05daily\x18\b \x03(\v2\x15.location.v1.DayStatsR\x05daily\"\x83\x01\n" +
	"\bDayStats\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12#\n" +
	"\rjourney_count\x18\x02 \x01(\x05R\fjourneyCount\x12\x1d\n" +
	"\n" +
	"distance_m\x18\x03 \x01(\x01R\tdistanceM\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\"\x9b\x01\n" +
	"\x13SaveLocationRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x19\n" +
	"\bradius_m\x18\x05 \x01(\x02R\aradiusM\"\xc4\x01\n" +
	"\rSavedLocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x19\n" +
	"\bradius_m\x18\x06 \x01(\x02R\aradiusM\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"7\n" +
	"\x18GetSavedLocationsRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"U\n" +
	"\x19GetSavedLocationsResponse\x128\n" +
	"\tlocations\x18\x01 \x03(\v2\x1a.location.v1.SavedLocationR\tlocations\"=\n" +
	"\x1aDeleteSavedLocationRequest\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\tR\n" +
	"locationId\"^\n" +
	"\x16CreateShareLinkRequest\x12\x1d\n" +
	"\n" +
	"journey_id\x18\x01 \x01(\tR\tjourneyId\x12%\n" +
	"\x0eduration_hours\x18\x02 \x01(\x03R\rdurationHours\"\x85\x01\n" +
	"\tShareLink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"journey_id\x18\x02 \x01(\tR\tjourneyId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\x12\x18\n" +
	"\aexpired\x18\x05 \x01(\bR\aexpired\"0\n" +
	"\x13GetShareLinkRequest\x12\x19\n" +
	"\bshare_id\x18\x01 \x01(\tR\ashareId\"F\n" +
	"\rExportRequest\x12\x1d\n" +
	"\n" +
	"journey_id\x18\x01 \x01(\tR\tjourneyId\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"@\n" +
	"\x0eExportResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"}\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x1b\n" +
	"\tlast_seen\x18\x04 \x01(\x03R\blastSeen\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\"\x13\n" +
	"\x11GetDevicesRequest\"C\n" +
	"\x12GetDevicesResponse\x12-\n" +
	"\adevices\x18\x01 \x03(\v2\x13.location.v1.DeviceR\adevices\"\a\n" +
	"\x05Empty2\xe1\t\n" +
	"\x0fLocationService\x12J\n" +
	"\x0fStreamLocations\x12\x1b.location.v1.LocationUpdate\x1a\x18.location.v1.LocationAck(\x01\x12F\n" +
	"\fStartJourney\x12 .location.v1.StartJourneyRequest\x1a\x14.location.v1.Journey\x12B\n" +
	"\n" +
	"EndJourney\x12\x1e.location.v1.EndJourneyRequest\x1a\x14.location.v1.Journey\x12P\n" +
	"\vGetJourneys\x12\x1f.location.v1.GetJourneysRequest\x1a .location.v1.GetJourneysResponse\x12_\n" +
	"\x10GetJourneyPoints\x12$.location.v1.GetJourneyPointsRequest\x1a%.location.v1.GetJourneyPointsResponse\x12T\n" +
	"\x11RequestDeviceCode\x12\x1e.location.v1.DeviceCodeRequest\x1a\x1f.location.v1.DeviceCodeResponse\x12a\n" +
	"\x14PollDeviceActivation\x12\".location.v1.PollActivationRequest\x1a%.location.v1.DeviceActivationResponse\x12Q\n" +
	"\x0fGetJourneyStats\x12#.location.v1.GetJourneyStatsRequest\x1a\x19.location.v1.JourneyStats\x12L\n" +
	"\fSaveLocation\x12 .location.v1.SaveLocationRequest\x1a\x1a.location.v1.SavedLocation\x12b\n" +
	"\x11GetSavedLocations\x12%.location.v1.GetSavedLocationsRequest\x1a&.location.v1.GetSavedLocationsResponse\x12R\n" +
	"\x13DeleteSavedLocation\x12'.location.v1.DeleteSavedLocationRequest\x1a\x12.location.v1.Empty\x12N\n" +
	"\x0fCreateShareLink\x12#.location.v1.CreateShareLinkRequest\x1a\x16.location.v1.ShareLink\x12H\n" +
	"\fGetShareLink\x12 .location.v1.GetShareLinkRequest\x1a\x16.location.v1.ShareLink\x12H\n" +
	"\rExportJourney\x12\x1a.location.v1.ExportRequest\x1a\x1b.location.v1.ExportResponse\x12M\n" +
	"\n" +
	"GetDevices\x12\x1e.location.v1.GetDevicesRequest\x1a\x1f.location.v1.GetDevicesResponseB\"Z bwhere/pb/location/v1;locationv1b\x06proto3"

var (
	file_location_v1_location_proto_rawDescOnce sync.Once
	file_location_v1_location_proto_rawDescData []byte
)

func file_location_v1_location_proto_rawDescGZIP() []byte {
	file_location_v1_location_proto_rawDescOnce.Do(func() {
		file_location_v1_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_location_v1_location_proto_rawDesc), len(file_location_v1_location_proto_rawDesc)))
	})
	return file_location_v1_location_proto_rawDescData
}

var file_location_v1_location_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_location_v1_location_proto_goTypes = []any{
	(*LocationUpdate)(nil),             // 0: location.v1.LocationUpdate
	(*LocationAck)(nil),                // 1: location.v1.LocationAck
	(*LocationPoint)(nil),              // 2: location.v1.LocationPoint
	(*StartJourneyRequest)(nil),        // 3: location.v1.StartJourneyRequest
	(*EndJourneyRequest)(nil),          // 4: location.v1.EndJourneyRequest
	(*Journey)(nil),                    // 5: location.v1.Journey
	(*GetJourneysRequest)(nil),         // 6: location.v1.GetJourneysRequest
	(*GetJourneysResponse)(nil),        // 7: location.v1.GetJourneysResponse
	(*GetJourneyPointsRequest)(nil),    // 8: location.v1.GetJourneyPointsRequest
	(*GetJourneyPointsResponse)(nil),   // 9: location.v1.GetJourneyPointsResponse
	(*DeviceCodeRequest)(nil),          // 10: location.v1.DeviceCodeRequest
	(*DeviceCodeResponse)(nil),         // 11: location.v1.DeviceCodeResponse
	(*PollActivationRequest)(nil),      // 12: location.v1.PollActivationRequest
	(*DeviceActivationResponse)(nil),   // 13: location.v1.DeviceActivationResponse
	(*GetJourneyStatsRequest)(nil),     // 14: location.v1.GetJourneyStatsRequest
	(*JourneyStats)(nil),               // 15: location.v1.JourneyStats
	(*DayStats)(nil),                   // 16: location.v1.DayStats
	(*SaveLocationRequest)(nil),        // 17: location.v1.SaveLocationRequest
	(*SavedLocation)(nil),              // 18: location.v1.SavedLocation
	(*GetSavedLocationsRequest)(nil),   // 19: location.v1.GetSavedLocationsRequest
	(*GetSavedLocationsResponse)(nil),  // 20: location.v1.GetSavedLocationsResponse
	(*DeleteSavedLocationRequest)(nil), // 21: location.v1.DeleteSavedLocationRequest
	(*CreateShareLinkRequest)(nil),     // 22: location.v1.CreateShareLinkRequest
	(*ShareLink)(nil),                  // 23: location.v1.ShareLink
	(*GetShareLinkRequest)(nil),        // 24: location.v1.GetShareLinkRequest
	(*ExportRequest)(nil),              // 25: location.v1.ExportRequest
	(*ExportResponse)(nil),             // 26: location.v1.ExportResponse
	(*Device)(nil),                     // 27: location.v1.Device
	(*GetDevicesRequest)(nil),          // 28: location.v1.GetDevicesRequest
	(*GetDevicesResponse)(nil),         // 29: location.v1.GetDevicesResponse
	(*Empty)(nil),                      // 30: location.v1.Empty
}
var file_location_v1_location_proto_depIdxs = []int32{
	5,  // 0: location.v1.GetJourneysResponse.journeys:type_name -> location.v1.Journey
	2,  // 1: location.v1.GetJourneyPointsResponse.points:type_name -> location.v1.LocationPoint
	16, // 2: location.v1.JourneyStats.daily:type_name -> location.v1.DayStats
	18, // 3: location.v1.GetSavedLocationsResponse.locations:type_name -> location.v1.SavedLocation
	27, // 4: location.v1.GetDevicesResponse.devices:type_name -> location.v1.Device
	0,  // 5: location.v1.LocationService.StreamLocations:input_type -> location.v1.LocationUpdate
	3,  // 6: location.v1.LocationService.StartJourney:input_type -> location.v1.StartJourneyRequest
	4,  // 7: location.v1.LocationService.EndJourney:input_type -> location.v1.EndJourneyRequest
	6,  // 8: location.v1.LocationService.GetJourneys:input_type -> location.v1.GetJourneysRequest
	8,  // 9: location.v1.LocationService.GetJourneyPoints:input_type -> location.v1.GetJourneyPointsRequest
	10, // 10: location.v1.LocationService.RequestDeviceCode:input_type -> location.v1.DeviceCodeRequest
	12, // 11: location.v1.LocationService.PollDeviceActivation:input_type -> location.v1.PollActivationRequest
	14, // 12: location.v1.LocationService.GetJourneyStats:input_type -> location.v1.GetJourneyStatsRequest
	17, // 13: location.v1.LocationService.SaveLocation:input_type -> location.v1.SaveLocationRequest
	19, // 14: location.v1.LocationService.GetSavedLocations:input_type -> location.v1.GetSavedLocationsRequest
	21, // 15: location.v1.LocationService.DeleteSavedLocation:input_type -> location.v1.DeleteSavedLocationRequest
	22, // 16: location.v1.LocationService.CreateShareLink:input_type -> location.v1.CreateShareLinkRequest
	24, // 17: location.v1.LocationService.GetShareLink:input_type -> location.v1.GetShareLinkRequest
	25, // 18: location.v1.LocationService.ExportJourney:input_type -> location.v1.ExportRequest
	28, // 19: location.v1.LocationService.GetDevices:input_type -> location.v1.GetDevicesRequest
	1,  // 20: location.v1.LocationService.StreamLocations:output_type -> location.v1.LocationAck
	5,  // 21: location.v1.LocationService.StartJourney:output_type -> location.v1.Journey
	5,  // 22: location.v1.LocationService.EndJourney:output_type -> location.v1.Journey
	7,  // 23: location.v1.LocationService.GetJourneys:output_type -> location.v1.GetJourneysResponse
	9,  // 24: location.v1.LocationService.GetJourneyPoints:output_type -> location.v1.GetJourneyPointsResponse
	11, // 25: location.v1.LocationService.RequestDeviceCode:output_type -> location.v1.DeviceCodeResponse
	13, // 26: location.v1.LocationService.PollDeviceActivation:output_type -> location.v1.DeviceActivationResponse
	15, // 27: location.v1.LocationService.GetJourneyStats:output_type -> location.v1.JourneyStats
	18, // 28: location.v1.LocationService.SaveLocation:output_type -> location.v1.SavedLocation
	20, // 29: location.v1.LocationService.GetSavedLocations:output_type -> location.v1.GetSavedLocationsResponse
	30, // 30: location.v1.LocationService.DeleteSavedLocation:output_type -> location.v1.Empty
	23, // 31: location.v1.LocationService.CreateShareLink:output_type -> location.v1.ShareLink
	23, // 32: location.v1.LocationService.GetShareLink:output_type -> location.v1.ShareLink
	26, // 33: location.v1.LocationService.ExportJourney:output_type -> location.v1.ExportResponse
	29, // 34: location.v1.LocationService.GetDevices:output_type -> location.v1.GetDevicesResponse
	20, // [20:35] is the sub-list for method output_type
	5,  // [5:20] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_location_v1_location_proto_init() }
func file_location_v1_location_proto_init() {
	if File_location_v1_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_location_v1_location_proto_rawDesc), len(file_location_v1_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_location_v1_location_proto_goTypes,
		DependencyIndexes: file_location_v1_location_proto_depIdxs,
		MessageInfos:      file_location_v1_location_proto_msgTypes,
	}.Build()
	File_location_v1_location_proto = out.File
	file_location_v1_location_proto_goTypes = nil
	file_location_v1_location_proto_depIdxs = nil
}
